// Anteater Location Data - UPDATED
const LOCATIONS = [
    {
      id: "zoo-001",
      name: "Abilene Zoo",
      address: "2070 Zoo Ln, Abilene, TX 79602",
      city: "Abilene",
      state: "TX",
      country: "USA",
      lat: 32.4487,
      lng: -99.7331,
      website: "https://www.abilenezoo.org",
      encounter: true,
      species: ["Giant Anteater"],
      notes: "Home to 'Demo' (mother) and her twin pups born in 2022 (first twins for the zoo). Exhibits are located in the South America area.",
      encounter_details: "Giant Anteater Tour: $25/person (3+). Tuesdays, Thursdays, Saturdays at 11:00 AM. 20-30 mins. Behind-the-scenes look at diet and adaptations. Unavailable Jan-March due to temps."
    },
    {
      id: "zoo-002",
      name: "Aggieland Safari",
      address: "4600 TX-21, Bryan, TX 77808",
      city: "Bryan",
      state: "TX",
      country: "USA",
      lat: 30.7235,
      lng: -96.2498,
      website: "https://www.aggielandsafari.com",
      encounter: false,
      species: ["Southern Tamandua"],
      notes: "Tamanduas are typically found in the Adventure Zoo's 'Nocturnal Hallway.'",
      encounter_details: "No specific tamandua encounter listed (capybara and otter encounters available)."
    },
    {
      id: "zoo-003",
      name: "Alabama Safari Park",
      address: "10950 US-80, Hamilton, AL 35570",
      city: "Hamilton",
      state: "AL",
      country: "USA",
      lat: 33.9012,
      lng: -87.9887,
      website: "https://www.alabamasafaripark.com",
      encounter: false,
      species: ["Giant Anteater"],
      notes: "The park participates in the 'Anteaters & Highways' conservation project in Brazil.",
      encounter_details: ""
    },
    {
      id: "zoo-004",
      name: "Alexandria Zoological Park",
      address: "3016 Masonic Dr, Alexandria, LA 71301",
      city: "Alexandria",
      state: "LA",
      country: "USA",
      lat: 31.3157,
      lng: -92.4523,
      website: "https://www.thealexandriazoo.com",
      encounter: false,
      species: ["Giant Anteater"],
      notes: "Located in the 'Amazon' exhibit area alongside jaguars and caimans.",
      encounter_details: ""
    },
    {
      id: "zoo-005",
      name: "Audubon Zoo",
      address: "6500 Magazine St, New Orleans, LA 70118",
      city: "New Orleans",
      state: "LA",
      country: "USA",
      lat: 29.9257,
      lng: -90.1367,
      website: "https://audubonnatureinstitute.org/zoo",
      encounter: false,
      species: ["Giant Anteater"],
      notes: "Part of the South American Pampas exhibit. No current public anteater encounter listed.",
      encounter_details: ""
    },
    {
      id: "zoo-006",
      name: "Austin Aquarium",
      address: "13530 US-183 N, Austin, TX 78750",
      city: "Austin",
      state: "TX",
      country: "USA",
      lat: 30.4604,
      lng: -97.7956,
      website: "https://www.austinaquarium.com",
      encounter: false,
      species: ["Southern Tamandua"],
      notes: "Tamanduas are part of the 'Rainforest' interactive exhibits.",
      encounter_details: "Encounters use a 'Token' system; while sloths and porcupines are listed, tamanduas are often featured as 'Animal Ambassadors' during general floor hours."
    },
    {
      id: "zoo-007",
      name: "Bergen County Zoo",
      address: "216 Forest Ave, Paramus, NJ 07652",
      city: "Paramus",
      state: "NJ",
      country: "USA",
      lat: 40.9448,
      lng: -74.0712,
      website: "https://www.co.bergen.nj.us/zoo",
      encounter: false,
      species: ["Giant Anteater"],
      notes: "Located in the South American section. The zoo focuses on New World species.",
      encounter_details: ""
    },
    {
      id: "zoo-008",
      name: "Big Joel's Safari",
      address: "19201 SW 377th St, Florida City, FL 33034",
      city: "Florida City",
      state: "FL",
      country: "USA",
      lat: 25.4423,
      lng: -80.5287,
      website: "https://www.bigjoel.com",
      encounter: false,
      species: ["Southern Tamandua"],
      notes: "Private facility; tamanduas are part of the 'Petting Zoo/Foot Safari' area.",
      encounter_details: "Sloth encounters available, but no specific tamandua encounter currently listed."
    },
    {
      id: "zoo-009",
      name: "Brandon's Promised Land Zoo",
      address: "2950 Nails Creek Rd, Abbeville, SC 29620",
      city: "Abbeville",
      state: "SC",
      country: "USA",
      lat: 34.1551,
      lng: -82.3987,
      website: "https://www.bransonspromisedlandzoo.com",
      encounter: true,
      species: ["Southern Tamandua"],
      notes: "Known for high levels of interaction with 'Animal Ambassadors.'",
      encounter_details: "VIP Gold Experience allows you to choose an animal for a private encounter; Tamanduas are frequently available options. Price varies by package (approx $100-$150)."
    },
    {
      id: "zoo-010",
      name: "Brevard Zoo",
      address: "8225 N Wickham Rd, Melbourne, FL 32940",
      city: "Melbourne",
      state: "FL",
      country: "USA",
      lat: 28.1566,
      lng: -80.6814,
      website: "https://www.brevardzoo.org",
      encounter: false,
      species: ["Giant Anteater"],
      notes: "Home to 'Boo' (female) and 'Abner' (male). They reside in the 'Rainforest Revealed' exhibit.",
      encounter_details: ""
    },
    {
      id: "zoo-011",
      name: "Brights Zoo",
      address: "225 Brights Zoo Rd, Limestone, TN 37681",
      city: "Limestone",
      state: "TN",
      country: "USA",
      lat: 36.2048,
      lng: -82.6384,
      website: "https://www.brightszoo.com",
      encounter: false,
      species: ["Giant Anteater", "Southern Tamandua"],
      notes: "Private family-owned zoo. Anteaters are housed in the Central/South American section.",
      encounter_details: ""
    },
    {
      id: "zoo-012",
      name: "Bronx Zoo",
      address: "2300 Southern Blvd, Bronx, NY 10460",
      city: "Bronx",
      state: "NY",
      country: "USA",
      lat: 40.8506,
      lng: -73.8769,
      website: "https://bronxzoo.com",
      encounter: false,
      species: ["Giant Anteater"],
      notes: "Located in the Children's Zoo area. Publicly viewable daily.",
      encounter_details: "Offers 'Wild Encounters,' but currently no specific public ticket for anteaters (mostly cheetahs, penguins, sloths)."
    },
    {
      id: "zoo-013",
      name: "Brookfield Zoo",
      address: "8400 W 31st St, Brookfield, IL 60513",
      city: "Brookfield",
      state: "IL",
      country: "USA",
      lat: 41.8325,
      lng: -87.8370,
      website: "https://www.czs.org/brookfield-zoo",
      encounter: false,
      species: ["Giant Anteater", "Southern Tamandua"],
      notes: "Home to 'Tulum' (female giant anteater). Housed in Tropic World: South America.",
      encounter_details: "No specific anteater encounter; has 'Wild Connections' for penguins and otters."
    },
    {
      id: "zoo-014",
      name: "Caldwell Zoo",
      address: "2203 Martin Luther King Blvd, Tyler, TX 75702",
      city: "Tyler",
      state: "TX",
      country: "USA",
      lat: 32.3418,
      lng: -95.3191,
      website: "https://www.caldwellzoo.org",
      encounter: false,
      species: ["Giant Anteater"],
      notes: "Exhibited in 'Amazon River's Edge.'",
      encounter_details: ""
    },
    {
      id: "zoo-015",
      name: "Charles Paddock Zoo",
      address: "9100 Morro Rd, Atascadero, CA 93422",
      city: "Atascadero",
      state: "CA",
      country: "USA",
      lat: 35.4949,
      lng: -120.6629,
      website: "https://www.charlespaddockzoo.org",
      encounter: false,
      species: ["Southern Tamandua"],
      notes: "Focuses on small-to-medium tropical species. Tamanduas are in the indoor/protected exhibits.",
      encounter_details: ""
    },
    {
      id: "zoo-016",
      name: "Chattanooga Zoo",
      address: "301 N Holtzclaw Ave, Chattanooga, TN 37404",
      city: "Chattanooga",
      state: "TN",
      country: "USA",
      lat: 35.0456,
      lng: -85.2802,
      website: "https://www.chattzoo.org",
      encounter: true,
      species: ["Giant Anteater"],
      notes: "Home to 'Betsy' and 'Pico.' They are known for being very food-motivated.",
      encounter_details: "Wild Encounter: $150. Includes feeding yogurt and potentially touching their noses. 30 minutes. Limited availability."
    },
    {
      id: "zoo-017",
      name: "Cincinnati Zoo & Botanical Gardens",
      address: "3400 Vine St, Cincinnati, OH 45220",
      city: "Cincinnati",
      state: "OH",
      country: "USA",
      lat: 39.1455,
      lng: -84.5084,
      website: "https://cincinnatizoo.org",
      encounter: true,
      species: ["Southern Tamandua"],
      notes: "Located in the Children’s Zoo. Tamanduas are used as 'Animal Ambassadors.'",
      encounter_details: "Private Animal Appearances: Can be booked for events starting at $300-$500. Not a standard walk-up ticketed encounter for individuals."
    },
    {
      id: "zoo-018",
      name: "Cleveland Metroparks Zoo",
      address: "3900 Wildlife Way, Cleveland, OH 44109",
      city: "Cleveland",
      state: "OH",
      country: "USA",
      lat: 41.4451,
      lng: -81.7121,
      website: "https://www.clevelandmetroparkszoo.com",
      encounter: false,
      species: ["Giant Anteater"],
      notes: "Housed in the 'RainForest' building. They have a detailed research profile on their anteaters.",
      encounter_details: ""
    },
    {
      id: "zoo-019",
      name: "Columbian Park Zoo",
      address: "1915 Scott St, Lafayette, IN 47904",
      city: "Lafayette",
      state: "IN",
      country: "USA",
      lat: 40.4317,
      lng: -86.8947,
      website: "https://www.lafayette.in.gov/zoo",
      encounter: true,
      species: ["Southern Tamandua"],
      notes: "Home to 'Digger' the tamandua. He is an ambassador animal.",
      encounter_details: "Wild Encounter: $100 (includes 2 people). Approx 30 mins. Includes watching an enrichment session and a touching opportunity. Available April-October."
    },
    {
      id: "zoo-020",
      name: "Columbus Zoo & Aquarium",
      address: "4850 W Powell Rd, Powell, OH 43065",
      city: "Powell",
      state: "OH",
      country: "USA",
      lat: 40.1578,
      lng: -83.1202,
      website: "https://www.columbuszoo.org",
      encounter: true,
      species: ["Southern Tamandua"],
      notes: "Tamanduas are part of the 'Adventure Cove' animal ambassador team.",
      encounter_details: "Wild Encounters Experience: $600 for up to 10 guests. Private tour that includes several ambassadors; tamanduas often rotate into this program."
    },
    {
        id: "zoo-021",
        name: "Connecticut's Beardsley Zoo",
        address: "1875 Noble Ave, Bridgeport, CT 06610",
        city: "Bridgeport",
        state: "CT",
        country: "USA",
        lat: 41.2001,
        lng: -73.1823,
        website: "https://beardsleyzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to 'Pana' (female) and 'E.O.' (male), named after entomologist E.O. Wilson. They have successfully bred multiple pups, including 'Mochilla' (now at Alexandria Zoo).",
        encounter_details: ""
      },
    
      {
        id: "zoo-022",
        name: "Creation Kingdom Zoo",
        address: "348 Clearview Circle, Ball Ground, GA 30107",
        city: "Ball Ground",
        state: "GA",
        country: "USA",
        lat: 34.3415,
        lng: -84.3766,
        website: "https://www.creationkingdomzoo.com",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Southern Tamanduas are featured in the zoo's educational programs. Often housed in indoor tropical exhibits.",
        encounter_details: ""
      },
    
      {
        id: "zoo-023",
        name: "Dallas World Aquarium",
        address: "1801 N Griffin St, Dallas, TX 75202",
        city: "Dallas",
        state: "TX",
        country: "USA",
        lat: 32.7876,
        lng: -96.8076,
        website: "https://www.dwazoo.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Exhibited in the Mundo Maya section. The aquarium is known for its multi-level rainforest recreation.",
        encounter_details: ""
      },
    
      {
        id: "zoo-024",
        name: "Dallas Zoo",
        address: "650 S R.L. Thornton Fwy, Dallas, TX 75203",
        city: "Dallas",
        state: "TX",
        country: "USA",
        lat: 32.7416,
        lng: -96.8161,
        website: "https://www.dallaszoo.com",
        encounter: false,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "Giant anteaters are typically in the 'Wilds of Africa' or South American areas. Tamanduas are often used as education ambassadors.",
        encounter_details: "Offers 'Backstage Safaris' (starting at $160-$180), but anteaters are not currently a guaranteed part of the rotation (rotates between elephants, predators, and lemurs)."
      },
    
      {
        id: "zoo-025",
        name: "Denver Zoo",
        address: "2300 Steele St, Denver, CO 80205",
        city: "Denver",
        state: "CO",
        country: "USA",
        lat: 39.7496,
        lng: -104.9512,
        website: "https://www.denverzoo.org",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Southern Tamanduas are kept as part of the Conservation Alliance's South American focus. Known as the 'stinkers of the forest' in zoo educational talks due to their scent glands.",
        encounter_details: ""
      },
    
      {
        id: "zoo-026",
        name: "Detroit Zoo",
        address: "8450 W 10 Mile Rd, Royal Oak, MI 48067",
        city: "Royal Oak",
        state: "MI",
        country: "USA",
        lat: 42.4802,
        lng: -83.1488,
        website: "https://detroitzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to 'Bissel' and 'Mojo.' They are located in the American Grasslands habitat.",
        encounter_details: ""
      },
    
      {
        id: "zoo-027",
        name: "DeYoung Family Zoo",
        address: "N5406 County Rd G, Wallace, MI 49893",
        city: "Wallace",
        state: "MI",
        country: "USA",
        lat: 45.6771,
        lng: -87.6037,
        website: "https://www.deyoungfamilyzoo.com",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Private zoo known for high-interaction exhibits, though no specific tamandua-only public booking is listed online.",
        encounter_details: ""
      },
    
      {
        id: "zoo-028",
        name: "Discovery Cove Orlando",
        address: "6000 Discovery Cove Way, Orlando, FL 32821",
        city: "Orlando",
        state: "FL",
        country: "USA",
        lat: 28.4206,
        lng: -81.4630,
        website: "https://www.discoverycove.com",
        encounter: true,
        species: ["Southern Tamandua"],
        notes: "Tamanduas are part of the 'Animal Ambassador' team and are often brought out for the 'Animal Trek.'",
        encounter_details: "Animal Trek: $79-$99 upgrade. Guests meet various ambassadors including birds, sloths, and tamanduas. 30-minute experience. Participants must be at least 6 years old."
      },
    
      {
        id: "zoo-029",
        name: "Disney's Animal Kingdom",
        address: "2901 Osceola Pkwy, Bay Lake, FL 32830",
        city: "Bay Lake",
        state: "FL",
        country: "USA",
        lat: 28.3553,
        lng: -81.5901,
        website: "https://disneyworld.disney.go.com/destinations/animal-kingdom",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the Oasis Exhibits (near the park entrance). The habitat features leafy canopies and tranquil pools. Known for running through sprinklers as enrichment.",
        encounter_details: ""
      },
    
      {
        id: "zoo-030",
        name: "El Paso Zoo",
        address: "4001 E Paisano Dr, El Paso, TX 79905",
        city: "El Paso",
        state: "TX",
        country: "USA",
        lat: 31.7720,
        lng: -106.4448,
        website: "https://www.elpasozoo.org",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Exhibited in the South America section. No currently active public encounter listed.",
        encounter_details: ""
      },
    
      {
        id: "zoo-031",
        name: "Electric City Aquarium & Reptile Den",
        address: "6 Ash St, Scranton, PA 18510",
        city: "Scranton",
        state: "PA",
        country: "USA",
        lat: 41.4090,
        lng: -75.6624,
        website: "https://www.electriccityaquarium.com",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "The facility features tamanduas alongside rainforest reptiles. They focus on education/ambassador animals.",
        encounter_details: ""
      },
    
      {
        id: "zoo-032",
        name: "Franklin Park Zoo",
        address: "1 Franklin Park Rd, Boston, MA 02121",
        city: "Boston",
        state: "MA",
        country: "USA",
        lat: 42.3023,
        lng: -71.0890,
        website: "https://www.zoonewengland.org/franklin-park-zoo",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Exhibited in the Tropical Forest pavilion. No specific public anteater feeding or encounter listed currently.",
        encounter_details: ""
      },
    
      {
        id: "zoo-033",
        name: "Fresno Chaffee Zoo",
        address: "894 W Belmont Ave, Fresno, CA 93728",
        city: "Fresno",
        state: "CA",
        country: "USA",
        lat: 36.7478,
        lng: -119.8009,
        website: "https://www.fresnochaffeezoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to 'Chive' (female) and her pup 'Ají' (born 2022). They participate in the Anteaters & Highways conservation program.",
        encounter_details: ""
      },
    
      {
        id: "zoo-034",
        name: "Great Bend-Brit Spaugh Zoo",
        address: "1214 Main St, Great Bend, KS 67530",
        city: "Great Bend",
        state: "KS",
        country: "USA",
        lat: 38.3556,
        lng: -98.7700,
        website: "https://www.greatbendks.net/zoo",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Home to 'Enzo' (male), a Southern Tamandua who serves as an education ambassador.",
        encounter_details: "Meet-and-greets occur during special events/keeper chats, but there is no regularly scheduled private encounter for purchase."
      },
    
      {
        id: "zoo-035",
        name: "Greensboro Science Center",
        address: "4301 Lawndale Dr, Greensboro, NC 27455",
        city: "Greensboro",
        state: "NC",
        country: "USA",
        lat: 36.1337,
        lng: -79.8399,
        website: "https://www.greensboroscience.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "The center previously housed a beloved anteater named 'Eury' who passed in 2023. The habitat remains part of the Animal Discovery Zoological Park.",
        encounter_details: ""
      },
    
      {
        id: "zoo-036",
        name: "Greenville Zoo",
        address: "150 Cleveland Park Dr, Greenville, SC 29601",
        city: "Greenville",
        state: "SC",
        country: "USA",
        lat: 34.8614,
        lng: -82.3821,
        website: "https://www.greenvillezoo.com",
        encounter: true,
        species: ["Giant Anteater"],
        notes: "Home to 'Anton' the Giant Anteater, known for eating over 35,000 insects daily.",
        encounter_details: "Anteater Enrichment Encounter: $43.75+ per person. Must be requested 2 weeks in advance. Includes learning about and providing enrichment for the anteater."
      },
    
      {
        id: "zoo-037",
        name: "Gulf Breeze Zoo",
        address: "5701 Gulf Breeze Pkwy, Gulf Breeze, FL 32563",
        city: "Gulf Breeze",
        state: "FL",
        country: "USA",
        lat: 30.3819,
        lng: -87.0469,
        website: "https://www.gulfbreezezoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to 'Demetrio' and 'Alice.' They are exhibited in the South American Aviary area.",
        encounter_details: ""
      },
    
      {
        id: "zoo-038",
        name: "Happy Hollow Park & Zoo",
        address: "1300 Senter Rd, San Jose, CA 95112",
        city: "San Jose",
        state: "CA",
        country: "USA",
        lat: 37.3229,
        lng: -121.8467,
        website: "https://www.happyhollowpark.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Anteaters at Happy Hollow are fed a specialized pelleted diet plus oranges and avocado. Housed in the 'Zoo on the Hill' area.",
        encounter_details: ""
      },
    
      {
        id: "zoo-039",
        name: "Hattiesburg Zoo",
        address: "107 S 17th Ave, Hattiesburg, MS 39401",
        city: "Hattiesburg",
        state: "MS",
        country: "USA",
        lat: 31.3221,
        lng: -89.3078,
        website: "https://www.hattiesburgzoo.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Giant anteaters reside in the South American exhibit. No specific encounter listed for this species (sloth/lemur/wallaby encounters are the primary offerings).",
        encounter_details: ""
      },
    
      {
        id: "zoo-040",
        name: "Hillcrest Park Zoo",
        address: "2000 N Milt Phillips Ave, Seminole, OK 74868",
        city: "Seminole",
        state: "OK",
        country: "USA",
        lat: 35.2373,
        lng: -96.6710,
        website: "https://www.seminoleok.us/zoo",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "A smaller facility that focuses on education; tamanduas are part of the tropical mammal collection.",
        encounter_details: ""
      },
      {
        id: "zoo-041",
        name: "Houston Zoo",
        address: "6200 Hermann Park Dr, Houston, TX 77030",
        city: "Houston",
        state: "TX",
        country: "USA",
        lat: 29.7152,
        lng: -95.3900,
        website: "https://www.houstonzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the 'South America's Pantanal' exhibit. The zoo provides significant funding for the 'Anteaters & Highways' project in Brazil.",
        encounter_details: ""
      },
    
      {
        id: "zoo-042",
        name: "Jacksonville Zoo & Gardens",
        address: "370 Zoo Pkwy, Jacksonville, FL 32218",
        city: "Jacksonville",
        state: "FL",
        country: "USA",
        lat: 30.3988,
        lng: -81.6509,
        website: "https://www.jacksonvillezoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the 'Range of the Jaguar' South American loop. They often share space with other South American species in mixed-animal habitats.",
        encounter_details: ""
      },
    
      {
        id: "zoo-043",
        name: "John Ball Zoo",
        address: "1300 W Fulton St, Grand Rapids, MI 49504",
        city: "Grand Rapids",
        state: "MI",
        country: "USA",
        lat: 42.9612,
        lng: -85.6916,
        website: "https://www.jbzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Giant anteaters are housed in the South American habitat, recently integrated with Chacoan peccaries and capybaras.",
        encounter_details: ""
      },
    
      {
        id: "zoo-044",
        name: "Kentucky Down Under Adventure Zoo",
        address: "3700 L&N Turnpike Rd, Horse Cave, KY 42749",
        city: "Horse Cave",
        state: "KY",
        country: "USA",
        lat: 37.1788,
        lng: -85.9072,
        website: "https://www.kentuckydownunder.com",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "While famous for kangaroo interactions, they house tamanduas as part of their exotic animal collection, often seen in 'Animal Ambassador' chats.",
        encounter_details: ""
      },
    
      {
        id: "zoo-045",
        name: "Keystone Safari",
        address: "300 Critchlow Rd, Grove City, PA 16127",
        city: "Grove City",
        state: "PA",
        country: "USA",
        lat: 41.1651,
        lng: -80.1059,
        website: "https://www.keystonesafari.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to parents 'Helga' and 'Hugo.' Helga was actually raised at the facility. They recently celebrated the birth of a pup in late 2025.",
        encounter_details: ""
      },
    
      {
        id: "zoo-046",
        name: "Lee Richardson Zoo",
        address: "312 Finnup Dr, Garden City, KS 67846",
        city: "Garden City",
        state: "KS",
        country: "USA",
        lat: 37.9785,
        lng: -100.8724,
        website: "https://www.leerichardsonzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to a female giant anteater named 'Chili.' She can be found in the South American Pampas exhibit.",
        encounter_details: ""
      },
    
      {
        id: "zoo-047",
        name: "Lincoln's Children's Zoo",
        address: "1222 S 27th St, Lincoln, NE 68502",
        city: "Lincoln",
        state: "NE",
        country: "USA",
        lat: 40.7988,
        lng: -96.7066,
        website: "https://www.lincolnzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to 'Maisy' (mother) and 'Asterix' (father). They had a pup named 'Lancaster' in 2022. Pups are often visible for limited morning hours.",
        encounter_details: ""
      },
    
      {
        id: "zoo-048",
        name: "Little Rock Zoo",
        address: "1 Zoo Dr, Little Rock, AR 72205",
        city: "Little Rock",
        state: "AR",
        country: "USA",
        lat: 34.7331,
        lng: -92.3591,
        website: "https://www.littlerockzoo.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located across from the Duiker exhibit in the South America section. Known for using their claws to tear into logs provided by keepers.",
        encounter_details: ""
      },
    
      {
        id: "zoo-049",
        name: "Los Angeles Zoo & Botanical Gardens",
        address: "5333 Zoo Dr, Los Angeles, CA 90027",
        city: "Los Angeles",
        state: "CA",
        country: "USA",
        lat: 34.1483,
        lng: -118.2873,
        website: "https://www.lazoo.org",
        encounter: false,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "The tamanduas are often utilized as education animals. Giant anteaters are in a large naturalistic habitat within the South America section.",
        encounter_details: ""
      },
    
      {
        id: "zoo-050",
        name: "Lupa Zoo",
        address: "784 Exchange St, West Brookfield, MA 01585",
        city: "West Brookfield",
        state: "MA",
        country: "USA",
        lat: 42.2323,
        lng: -72.0534,
        website: "https://www.lupazoo.com",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "A smaller facility where tamanduas are part of a diverse collection of South American mammals.",
        encounter_details: ""
      },
    
      {
        id: "zoo-051",
        name: "Memphis Zoo",
        address: "2000 Prentiss Pl, Memphis, TN 38112",
        city: "Memphis",
        state: "TN",
        country: "USA",
        lat: 35.1497,
        lng: -90.0334,
        website: "https://www.memphiszoo.org",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Tamanduas are housed in the 'Cat Country' loop (which features many South American species) or the Tropical Bird House area as ambassadors.",
        encounter_details: ""
      },
    
      {
        id: "zoo-052",
        name: "Mesker Park Zoo & Botanical Garden",
        address: "1545 Mesker Park Dr, Evansville, IN 47720",
        city: "Evansville",
        state: "IN",
        country: "USA",
        lat: 37.9773,
        lng: -87.6226,
        website: "https://www.meskerparkzoo.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Housed in the 'Amazonia' exhibit, a 20,000 sq ft climate-controlled rainforest biome.",
        encounter_details: ""
      },
    
      {
        id: "zoo-053",
        name: "Metro Richmond Zoo",
        address: "8300 Beaver Bridge Rd, Moseley, VA 23120",
        city: "Moseley",
        state: "VA",
        country: "USA",
        lat: 37.4115,
        lng: -77.7354,
        website: "https://www.metrorichmondzoo.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Known for successful breeding programs. Anteaters are part of the South American walk-through areas.",
        encounter_details: ""
      },
    
      {
        id: "zoo-054",
        name: "Miller Park Zoo",
        address: "1020 S Morris Ave, Bloomington, IL 61701",
        city: "Bloomington",
        state: "IL",
        country: "USA",
        lat: 40.4710,
        lng: -88.9900,
        website: "https://www.millerparkzoo.org",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Features a breeding pair of Southern Tamanduas located in the Tropical Rainforest building. They also serve as ambassador animals for classes.",
        encounter_details: ""
      },
    
      {
        id: "zoo-055",
        name: "Montgomery Zoo & Mann Wildlife Learning Museum",
        address: "2301 Coliseum Pkwy, Montgomery, AL 36110",
        city: "Montgomery",
        state: "AL",
        country: "USA",
        lat: 32.3914,
        lng: -86.2522,
        website: "https://www.montgomeryzoo.com",
        encounter: true,
        species: ["Giant Anteater"],
        notes: "Home to several anteaters including 'Navy', 'Chickpea', 'Lima', and 'Green Bean.' Located in the South America/Africa border area.",
        encounter_details: "Maned Wolves/Giant Anteater Chat: Scheduled at 1:30 PM (varies by day). While it's a 'chat' and not a private hands-on ticket, keepers often provide enrichment during this time for public viewing."
      },
    
      {
        id: "zoo-056",
        name: "Moody Gardens",
        address: "1 Hope Blvd, Galveston, TX 77554",
        city: "Galveston",
        state: "TX",
        country: "USA",
        lat: 29.2796,
        lng: -94.8677,
        website: "https://www.moodygardens.com",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Located in the Rainforest Pyramid. While they have otter and penguin encounters, the tamanduas are currently display-only or random ambassador sightings.",
        encounter_details: ""
      },
    
      {
        id: "zoo-057",
        name: "Naples Zoo",
        address: "1590 Goodlette-Frank Rd N, Naples, FL 34102",
        city: "Naples",
        state: "FL",
        country: "USA",
        lat: 26.1544,
        lng: -81.7942,
        website: "https://www.napleszoo.org",
        encounter: true,
        species: ["Giant Anteater"],
        notes: "Home to 'Dee Gee' the Giant Anteater.",
        encounter_details: "Wild Encounter: $100+ per person. Guests go behind the scenes to learn about conservation and assist in feeding Dee Gee (yogurt/special diet). Participants must be 5+."
      },
    
      {
        id: "zoo-058",
        name: "Nashville Zoo",
        address: "3777 Nolensville Pike, Nashville, TN 37211",
        city: "Nashville",
        state: "TN",
        country: "USA",
        lat: 36.0896,
        lng: -86.7416,
        website: "https://www.nashvillezoo.org",
        encounter: true,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "Home to 'Andre' the Tamandua, a famous star of their 'WildWorks' show. The zoo is a world leader in giant anteater breeding.",
        encounter_details: "Backstage Pass: While Giant Anteaters are a staple, specific species interaction depends on the 'Animal Ambassador' rotation. Andre the Tamandua frequently meets guests after shows."
      },
    
      {
        id: "zoo-059",
        name: "North Florida Wildlife Center",
        address: "5400 Chuluota Rd, Christmas, FL 32709",
        city: "Christmas",
        state: "FL",
        country: "USA",
        lat: 28.5411,
        lng: -81.0249,
        website: "https://www.northfloridawildlifecenter.org",
        encounter: true,
        species: ["Giant Anteater"],
        notes: "Focuses heavily on up-close conservation experiences. Home to 'Eury' (referencing lineage) or current residents.",
        encounter_details: "Giant Anteater Encounter: $150 per person. A private experience that includes entering the habitat area, learning about their specialized diet, and a feeding opportunity."
      },
    
      {
        id: "zoo-060",
        name: "Palm Beach Zoo",
        address: "1301 Summit Blvd, West Palm Beach, FL 33405",
        city: "West Palm Beach",
        state: "FL",
        country: "USA",
        lat: 26.6839,
        lng: -80.0756,
        website: "https://www.palmbeachzoo.org",
        encounter: true,
        species: ["Giant Anteater"],
        notes: "Home to giant anteaters in the Tropics section. They are known for their 'Safari Nights' events where animals are more active.",
        encounter_details: "Interactive Experiences: The zoo periodically offers 'Anteater Experiences' (approx $50 upgrade) where guests can watch a training session and ask keeper questions."
      },
    
      {
        id: "zoo-061",
        name: "Pana'ewa Rainforest Zoo",
        address: "800 Stainback Hwy, Hilo, HI 96720",
        city: "Hilo",
        state: "HI",
        country: "USA",
        lat: 19.6528,
        lng: -155.0752,
        website: "https://www.hilozoo.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "The only tropical rainforest zoo in the US. Anteaters are part of a lush, naturalistic South American collection.",
        encounter_details: ""
      },
    
      {
        id: "zoo-062",
        name: "Phoenix Zoo",
        address: "455 N Galvin Pkwy, Phoenix, AZ 85008",
        city: "Phoenix",
        state: "AZ",
        country: "USA",
        lat: 33.4502,
        lng: -111.9468,
        website: "https://www.phoenixzoo.org",
        encounter: false,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "Giant anteaters can be found along the 'Tropics Trail.' Tamanduas are part of the 'Harmony Farm' or education ambassador group.",
        encounter_details: ""
      },
    
      {
        id: "zoo-063",
        name: "Pittsburgh Zoo & Aquarium",
        address: "7370 Baker St, Pittsburgh, PA 15206",
        city: "Pittsburgh",
        state: "PA",
        country: "USA",
        lat: 40.4853,
        lng: -79.9221,
        website: "https://www.pittsburghzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the 'Tropical Forest' area. No current private encounter available for purchase.",
        encounter_details: ""
      },
    
      {
        id: "zoo-064",
        name: "Point Defiance Zoo & Aquarium",
        address: "5400 N Pearl St, Tacoma, WA 98407",
        city: "Tacoma",
        state: "WA",
        country: "USA",
        lat: 47.3194,
        lng: -122.5243,
        website: "https://www.pdza.org",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Tamanduas are featured in the 'Wild Wonders Outdoor Theater' show. One of their famous residents is 'Gonza.'",
        encounter_details: "Public show appearances daily; no private/paid encounter currently listed."
      },
    
      {
        id: "zoo-065",
        name: "Potawatomi Zoo",
        address: "500 S Greenlawn Ave, South Bend, IN 46615",
        city: "South Bend",
        state: "IN",
        country: "USA",
        lat: 41.6670,
        lng: -86.2349,
        website: "https://www.potawatomizoo.org",
        encounter: true,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "Home to 'Inca' (female) and 'Corri' (male). They recently moved into a new South American habitat.",
        encounter_details: "Anteater Encounter: $75 per person. Includes a behind-the-scenes look at their habitat and a chance to provide enrichment. Seasonal availability (typically May-Sept)."
      },
    
      {
        id: "zoo-066",
        name: "Potter Park Zoo",
        address: "1301 S Pennsylvania Ave, Lansing, MI 48912",
        city: "Lansing",
        state: "MI",
        country: "USA",
        lat: 42.7156,
        lng: -84.5467,
        website: "https://www.potterparkzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Housed in the South American section. The zoo is very active in the SSP (Species Survival Plan) for giant anteaters.",
        encounter_details: ""
      },
    
      {
        id: "zoo-067",
        name: "Reid Park Zoo",
        address: "3400 Zoo Ct, Tucson, AZ 85716",
        city: "Tucson",
        state: "AZ",
        country: "USA",
        lat: 32.2104,
        lng: -110.9202,
        website: "https://reidparkzoo.org",
        encounter: true,
        species: ["Giant Anteater"],
        notes: "Home to 'Xochi' (female) and 'Zander' (male). They recently welcomed a pup named 'Lupa' (born 2023).",
        encounter_details: "Behind-the-Scenes Tour: $95+. Can be customized to focus on the South American animals including the anteaters, depending on animal health and staff availability."
      },
      {
        id: "zoo-068",
        name: "Roger Williams Park Zoo",
        address: "1000 Elmwood Ave, Providence, RI 02907",
        city: "Providence",
        state: "RI",
        country: "USA",
        lat: 41.7748,
        lng: -71.4227,
        website: "https://www.rwpzoo.org",
        encounter: false,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "Home to Giant Anteaters 'Delilah' and 'Corwin.' The tamanduas are often featured in the 'Faces of the Rainforest' exhibit, which mimics an Amazonian environment.",
        encounter_details: ""
      },
    
      {
        id: "zoo-069",
        name: "Rolling Hills Zoo",
        address: "625 N Hedville Rd, Salina, KS 67401",
        city: "Salina",
        state: "KS",
        country: "USA",
        lat: 38.8738,
        lng: -97.6801,
        website: "https://www.rollinghillswildlife.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the South American area. Known for 'Dimitri' (male). The exhibit features a large outdoor yard and a climate-controlled indoor viewing area.",
        encounter_details: ""
      },
    
      {
        id: "zoo-070",
        name: "Rosamond Gifford Zoo",
        address: "1 Conservation Pl, Syracuse, NY 13204",
        city: "Syracuse",
        state: "NY",
        country: "USA",
        lat: 43.0521,
        lng: -76.1574,
        website: "https://rosamondgiffordzoo.org",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Home to 'Mochi.' Found in the USS Antique exhibit (nocturnal/indoor rainforest section).",
        encounter_details: ""
      },
    
      {
        id: "zoo-071",
        name: "Sacramento Zoo",
        address: "3930 W Land Park Dr, Sacramento, CA 95822",
        city: "Sacramento",
        state: "CA",
        country: "USA",
        lat: 38.5491,
        lng: -121.5050,
        website: "https://www.saczoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to 'Inca.' The habitat is located near the entrance of the zoo in a lush, shaded area.",
        encounter_details: ""
      },
    
      {
        id: "zoo-072",
        name: "Saint Louis Aquarium at Union Station",
        address: "201 S 18th St, St. Louis, MO 63103",
        city: "St. Louis",
        state: "MO",
        country: "USA",
        lat: 38.6274,
        lng: -90.2045,
        website: "https://www.stlouisaquarium.com",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Home to 'Mochi' the tamandua. Located in the 'Global Rivers' area. While highly visible, there is no public ticketed encounter.",
        encounter_details: ""
      },
    
      {
        id: "zoo-073",
        name: "Saint Louis Zoo",
        address: " government Dr, St. Louis, MO 63110",
        city: "St. Louis",
        state: "MO",
        country: "USA",
        lat: 38.6352,
        lng: -90.2900,
        website: "https://www.stlzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the 'River’s Edge' exhibit, specifically the South American section alongside bush dogs and capybaras.",
        encounter_details: ""
      },
    
      {
        id: "zoo-074",
        name: "San Antonio Aquarium",
        address: "6320 Bandera Rd, Leon Valley, TX 78238",
        city: "Leon Valley",
        state: "TX",
        country: "USA",
        lat: 29.4996,
        lng: -98.6260,
        website: "https://www.sanantonioquarium.com",
        encounter: true,
        species: ["Southern Tamandua"],
        notes: "Tamanduas are part of the 'Rainforest' exhibit floor.",
        encounter_details: "Interaction Tokens: Guests can purchase tokens (approx $20-$30 value) to feed or pet certain rainforest animals. Tamanduas are frequently available as part of the 'Animal Ambassador' rotation."
      },
    
      {
        id: "zoo-075",
        name: "San Antonio Zoo",
        address: "3903 N St Mary's St, San Antonio, TX 78212",
        city: "San Antonio",
        state: "TX",
        country: "USA",
        lat: 29.4604,
        lng: -98.4717,
        website: "https://www.sazoo.org",
        encounter: false,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "Located in the 'Kronkosky Tiny Tot Nature Spot' and 'Neotropica.' No public feeding/encounter currently listed.",
        encounter_details: ""
      },
    
      {
        id: "zoo-076",
        name: "San Diego Zoo",
        address: "2920 Zoo Dr, San Diego, CA 92101",
        city: "San Diego",
        state: "CA",
        country: "USA",
        lat: 32.7353,
        lng: -117.1490,
        website: "https://zoo.sandiegozoo.org",
        encounter: false,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "Famous for 'Cinco' and 'Xena.' Located in the Elephant Odyssey (mixed species) and the Lost Forest. While they have many 'Exclusive Extras,' none currently feature anteaters specifically.",
        encounter_details: ""
      },
    
      {
        id: "zoo-077",
        name: "San Diego Zoo Safari Park",
        address: "15500 San Pasqual Valley Rd, Escondido, CA 92027",
        city: "Escondido",
        state: "CA",
        country: "USA",
        lat: 33.0977,
        lng: -116.9981,
        website: "https://www.sdzsafaripark.org",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Tamanduas are part of the 'Walkabout Australia' and 'Nairobi Village' ambassador groups. Frequently seen during 'Wildlife Wonders' presentations.",
        encounter_details: ""
      },
    
      {
        id: "zoo-078",
        name: "San Francisco Zoo",
        address: "Sloat Blvd & Great Hwy, San Francisco, CA 94132",
        city: "San Francisco",
        state: "CA",
        country: "USA",
        lat: 37.7325,
        lng: -122.5026,
        website: "https://www.sfzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in South America's Tropical Rainforest and Aviary. Housed near the capybaras.",
        encounter_details: ""
      },
    
      {
        id: "zoo-079",
        name: "Santa Ana Zoo",
        address: "1801 E Chestnut Ave, Santa Ana, CA 92701",
        city: "Santa Ana",
        state: "CA",
        country: "USA",
        lat: 33.7351,
        lng: -117.8604,
        website: "https://www.santaanazoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Part of the Tierney South America Trek. Features a breeding pair that contributes to the SSP.",
        encounter_details: ""
      },
    
      {
        id: "zoo-080",
        name: "Santa Barbara Zoo",
        address: "500 Niños Dr, Santa Barbara, CA 93103",
        city: "Santa Barbara",
        state: "CA",
        country: "USA",
        lat: 34.4107,
        lng: -119.6683,
        website: "https://www.sbzoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the 'Discovery Outpost.' Noted for their unique 'ant-hill' style enrichment feeders.",
        encounter_details: ""
      },
    
      {
        id: "zoo-081",
        name: "Sedgwick County Zoo",
        address: "5555 Zoo Blvd, Wichita, KS 67212",
        city: "Wichita",
        state: "KS",
        country: "USA",
        lat: 37.7195,
        lng: -97.4003,
        website: "https://www.scz.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the Tropical America building. No public encounter listed (only for penguins/giraffes).",
        encounter_details: ""
      },
    
      {
        id: "zoo-082",
        name: "Six Flags Great Adventure Wild Safari",
        address: "1 Six Flags Blvd, Jackson, NJ 08527",
        city: "Jackson",
        state: "NJ",
        country: "USA",
        lat: 40.1357,
        lng: -74.4368,
        website: "https://www.sixflags.com/greatadventure/safari",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Viewable from the drive-through safari in the 'Americas' section. Often seen foraging in the open grass areas.",
        encounter_details: ""
      },
    
      {
        id: "zoo-083",
        name: "Smithsonian National Zoo",
        address: "3001 Connecticut Ave NW, Washington, DC 20008",
        city: "Washington",
        state: "DC",
        country: "USA",
        lat: 38.9297,
        lng: -77.0498,
        website: "https://nationalzoo.si.edu",
        encounter: false,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "Giant anteaters reside on the 'American Trail.' Tamanduas are located in the 'Amazonia' exhibit. Known for 'Dante' and 'Maripi.'",
        encounter_details: ""
      },
    
      {
        id: "zoo-084",
        name: "Staten Island Zoo",
        address: "614 Broadway, Staten Island, NY 10310",
        city: "Staten Island",
        state: "NY",
        country: "USA",
        lat: 40.6273,
        lng: -74.1151,
        website: "https://www.statenislandzoo.org",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Housed in the tropical forest section. Tamanduas are frequently used in the zoo's virtual and traveling educational programs.",
        encounter_details: ""
      },
    
      {
        id: "zoo-085",
        name: "Summerfield Zoo",
        address: "W3180 Potter Rd, Janesville, WI 53548",
        city: "Summerfield",
        state: "WI",
        country: "USA",
        lat: 42.7143,
        lng: -89.0551,
        website: "https://www.summerfieldzoo.com",
        encounter: true,
        species: ["Southern Tamandua"],
        notes: "A smaller, highly interactive zoo. Known for their 'Ambassador' animals.",
        encounter_details: "Private Animal Encounter: $50-$100 (plus admission). Tamanduas are listed as a bookable species for up-close educational sessions. Must be booked in advance."
      },
    
      {
        id: "zoo-086",
        name: "Sunset Zoo",
        address: "2333 Oak St, Manhattan, KS 66502",
        city: "Manhattan",
        state: "KS",
        country: "USA",
        lat: 39.1864,
        lng: -96.6002,
        website: "https://www.sunsetzoo.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the 'South American Pampas' area. No current ticketed encounter.",
        encounter_details: ""
      },
    
      {
        id: "zoo-087",
        name: "Sustainable Safari at Maplewood Mall",
        address: "3001 White Bear Ave N, Maplewood, MN 55109",
        city: "Maplewood",
        state: "MN",
        country: "USA",
        lat: 45.0219,
        lng: -93.0246,
        website: "https://www.sustainablesafari.com",
        encounter: true,
        species: ["Southern Tamandua"],
        notes: "A mall-based interactive zoo. Features tamanduas as major attractions.",
        encounter_details: "Interaction Package: General admission + approx $15-$20 for interaction. Guests can pet and take photos with tamanduas during scheduled 'handling' times throughout the day."
      },
    
      {
        id: "zoo-088",
        name: "Tanganyika Wildlife Park",
        address: "1000 S Hawkins Ln, Goddard, KS 67052",
        city: "Goddard",
        state: "KS",
        country: "USA",
        lat: 37.6614,
        lng: -97.5698,
        website: "https://www.twpark.com",
        encounter: true,
        species: ["Giant Anteater"],
        notes: "One of the most interactive zoos in the country. Known for their 'Anteater and Avocado' sessions.",
        encounter_details: "Anteater Meet & Greet: Part of the 'Best Day Ever' or 'Ultimate Weekend' packages ($150+). Includes feeding avocados to giant anteaters. Available seasonally."
      },
    
      {
        id: "zoo-089",
        name: "The Birmingham Zoo",
        address: "2630 Cahaba Rd, Birmingham, AL 35223",
        city: "Birmingham",
        state: "AL",
        country: "USA",
        lat: 33.4894,
        lng: -86.7799,
        website: "https://www.birminghamzoo.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the South American habitat. No public encounter listed (focuses on rhino/giraffe/sloth).",
        encounter_details: ""
      },
    
      {
        id: "zoo-090",
        name: "The Buffalo Zoo",
        address: "300 Parkside Ave, Buffalo, NY 14214",
        city: "Buffalo",
        state: "NY",
        country: "USA",
        lat: 42.9323,
        lng: -78.8648,
        website: "https://www.buffalozoo.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to 'Ketchikan' (male) and 'Aari' (female). Located in the 'Rainforest Falls' exhibit.",
        encounter_details: ""
      },
    
      {
        id: "zoo-091",
        name: "The Toledo Zoo",
        address: "2 Hippo Way, Toledo, OH 43609",
        city: "Toledo",
        state: "OH",
        country: "USA",
        lat: 41.6426,
        lng: -83.6068,
        website: "https://www.toledozoo.org",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Found in the Museum of Science/Indoor Rainforest area. Tamanduas are part of their educational outreach fleet.",
        encounter_details: ""
      },
    
      {
        id: "zoo-092",
        name: "Timbavati Wildlife Park",
        address: "W4156 WI-23, Wisconsin Dells, WI 53965",
        city: "Wisconsin Dells",
        state: "WI",
        country: "USA",
        lat: 43.6402,
        lng: -89.8040,
        website: "https://www.timbavatiwildlife.com",
        encounter: true,
        species: ["Southern Tamandua"],
        notes: "Private wildlife park with a focus on close-up encounters.",
        encounter_details: "VIP Tour: Prices start around $100. Allows for private time with various mammals; tamanduas are a common request/option for these sessions."
      },
    
      {
        id: "zoo-093",
        name: "Turtle Back Zoo",
        address: "560 Northfield Ave, West Orange, NJ 07052",
        city: "West Orange",
        state: "NJ",
        country: "USA",
        lat: 40.7929,
        lng: -74.2849,
        website: "https://www.turtlebackzoo.com",
        encounter: false,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "Giant anteaters are in the South American exhibit area. Tamanduas are often kept in the education center.",
        encounter_details: ""
      },
    
      {
        id: "zoo-094",
        name: "Virginia Safari Park",
        address: "229 Safari Ln, Natural Bridge, VA 24578",
        city: "Natural Bridge",
        state: "VA",
        country: "USA",
        lat: 37.6278,
        lng: -79.5357,
        website: "https://www.virginiasafaripark.com",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Visible in the village walk-through area (not the drive-through). Home to 'Demetrio.'",
        encounter_details: ""
      },
    
      {
        id: "zoo-095",
        name: "Washington Park Zoo",
        address: "500 Aquatic Dr, Michigan City, IN 46360",
        city: "Michigan City",
        state: "IN",
        country: "USA",
        lat: 41.7094,
        lng: -86.8792,
        website: "https://www.washingtonparkzoo.com",
        encounter: false,
        species: ["Southern Tamandua"],
        notes: "Located in the 'Amazon' area. No currently ticketed private interaction.",
        encounter_details: ""
      },
    
      {
        id: "zoo-096",
        name: "Zoo Boise",
        address: "355 N Julia Davis Dr, Boise, ID 83702",
        city: "Boise",
        state: "ID",
        country: "USA",
        lat: 43.6061,
        lng: -116.1922,
        website: "https://www.zooboise.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Located in the 'South American' exhibit. No anteater encounter (only for sloths/penguins).",
        encounter_details: ""
      },
    
      {
        id: "zoo-097",
        name: "Zoo Miami",
        address: "12400 SW 152nd St, Miami, FL 33177",
        city: "Miami",
        state: "FL",
        country: "USA",
        lat: 25.6040,
        lng: -80.3997,
        website: "https://www.zoomiami.org",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to 'Baron' (male) and 'Priscilla' (female). They are featured in the Amazon and Beyond section.",
        encounter_details: ""
      },
    
      {
        id: "zoo-098",
        name: "Zoological Wildlife Foundation Miami",
        address: "16225 SW 172nd Ave, Miami, FL 33187",
        city: "Miami",
        state: "FL",
        country: "USA",
        lat: 25.5614,
        lng: -80.4957,
        website: "https://www.zwfmiami.com",
        encounter: true,
        species: ["Giant Anteater", "Southern Tamandua"],
        notes: "A strictly by-appointment encounter facility. Home to 'Pili' the tamandua.",
        encounter_details: "Anteater/Tamandua Encounter: $100-$150. A private session that allows for up-close interaction and photo opportunities. Must be booked in advance."
      },
    
      {
        id: "zoo-099",
        name: "Miller Zoo",
        address: "20 Route 276, Frampton, QC G0R 1M0, Canada",
        city: "Frampton",
        state: "QC",
        country: "Canada",
        lat: 46.4632,
        lng: -70.7042,
        website: "https://millerzoo.ca",
        encounter: false,
        species: ["Giant Anteater"],
        notes: "Home to 'Xochi' and 'Lupa' (originally from US zoos). Located in the South American sector. Known for their rescue and rehabilitation focus.",
        encounter_details: ""
      },
    
      {
        id: "zoo-100",
        name: "Aluxes Palenque",
        address: "Carretera a la Zona Arqueológica Km 2, Palenque, Chiapas, Mexico",
        city: "Palenque",
        state: "Chiapas",
        country: "Mexico",
        lat: 17.5091,
        lng: -91.9567,
        website: "https://aluxes.org.mx",
        encounter: false,
        species: ["Northern Tamandua"],
        notes: "An ecopark specializing in the rescue and release of Chiapas wildlife. Tamanduas are often brought in for rehab.",
        encounter_details: ""
      },
    
      {
        id: "zoo-101",
        name: "Parque Zoológico del Centenario",
        address: "Av. Itzáes S/N, Mérida, Yucatán, Mexico",
        city: "Mérida",
        state: "Yucatán",
        country: "Mexico",
        lat: 20.9673,
        lng: -89.6385,
        website: "https://www.merida.gob.mx/municipio/portal/actividades/centenario.phpx",
        encounter: false,
        species: ["Northern Tamandua"],
        notes: "A free public park in Mérida. Tamanduas are located in the tropical mammals section. No private encounters.",
        encounter_details: ""
      },
    
      {
        id: "zoo-102",
        name: "Zoológico Miguel Álvarez del Toro (ZOOMAT)",
        address: "Calzada Cerro Hueco s/n, Tuxtla Gutiérrez, Chiapas, Mexico",
        city: "Tuxtla Gutiérrez",
        state: "Chiapas",
        country: "Mexico",
        lat: 16.7214,
        lng: -93.0934,
        website: "https://www.zoomat.com.mx",
        encounter: false,
        species: ["Northern Tamandua"],
        notes: "Unique for only housing species native to Chiapas. Tamanduas are kept in large semi-wild enclosures. No public encounters.",
        encounter_details: ""
      }      
  ];